sudo: required
language: php
php:
  - 7.1
services:
  - docker
before_install:
  - 'sed -i "s#image: fusio\/fusio#build: \.#g" docker-compose.yml'
  - 'sed -i "s#80:80#8080:80#g" docker-compose.yml'
  - 'sed -i "s#https:\/\/github\.com\/apioo\/fusio\/releases\/download\/v${FUSIO_VERSION}\/fusio_${FUSIO_VERSION}\.zip#https:\/\/github\.com\/apioo\/fusio\/archive\/master\.zip#g" docker-compose.yml'
  - 'sed -i "s# \| sha1sum \-c \-##g" docker-compose.yml'
install:
  - composer install
  - docker-compose up -d
  - 'while [[ $(curl -s -o /dev/null -w  "%{http_code}" localhost:8080) != "200" ]]; do sleep 5; done'
script:
  - vendor/bin/phpunit
