version: '2'
services:
  # Fusio container
  fusio:
    image: fusio/fusio
    environment:
      FUSIO_PROJECT_KEY: "42eec18ffdbffc9fda6110dcc705d6ce"
      FUSIO_URL: "http://localhost"
      FUSIO_ENV: "prod"
      FUSIO_DB_NAME: "fusio"
      FUSIO_DB_USER: "fusio"
      FUSIO_DB_PW: "61ad6c605975"
      FUSIO_DB_HOST: "mysql_fusio"
      FUSIO_MEMCACHE_HOST: "memcached"
      FUSIO_BACKEND_USER: "demo"
      FUSIO_BACKEND_EMAIL: "demo@fusio-project.org"
      FUSIO_BACKEND_PW: "75dafcb12c4f"
      APP_MYSQL_1_NAME: "app"
      APP_MYSQL_1_USER: "app"
      APP_MYSQL_1_PW: "57cd4fee0ed0"
      APP_MYSQL_1_HOST: "mysql_1"
    volumes:
      - ./fusio/public:/var/www/html/fusio/public
      - ./fusio/resources:/var/www/html/fusio/resources
      - ./fusio/src:/var/www/html/fusio/src
    links:
      - memcached
      - mysql_fusio
      - mysql_1
    ports:
      - "80:80"

  # Memcached container for caching
  memcached:
    image: memcached

  # Fusio system database
  mysql_fusio:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "7f3e5186032a"
      MYSQL_USER: "fusio"
      MYSQL_PASSWORD: "61ad6c605975"
      MYSQL_DATABASE: "fusio"
    volumes:
      - ./db/fusio:/var/lib/mysql

  # Mysql database for the app
  mysql_1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "290f0be801b3"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "57cd4fee0ed0"
      MYSQL_DATABASE: "app"
    volumes:
      - ./db/mysql-1:/var/lib/mysql
