version: '3'
services:
  # Fusio container
  fusio:
    image: fusio/fusio
    restart: always
    environment:
      FUSIO_PROJECT_KEY: "42eec18ffdbffc9fda6110dcc705d6ce"
      FUSIO_DOMAIN: "api.fusio.cloud"
      FUSIO_HOST: "api.fusio.cloud:8080"
      FUSIO_URL: "http://api.fusio.cloud:8080"
      FUSIO_APPS_URL: "http://api.fusio.cloud:8080/apps"
      FUSIO_ENV: "prod"
      FUSIO_DB_NAME: "fusio"
      FUSIO_DB_USER: "fusio"
      FUSIO_DB_PW: "61ad6c605975"
      FUSIO_DB_HOST: "mysql_fusio"
      FUSIO_BACKEND_USER: "demo"
      FUSIO_BACKEND_EMAIL: "demo@fusio-project.org"
      FUSIO_BACKEND_PW: "75dafcb12c4f"
      FUSIO_VERSION: "master"
      PROVIDER_FACEBOOK_KEY: ""
      PROVIDER_FACEBOOK_SECRET: ""
      PROVIDER_GOOGLE_KEY: ""
      PROVIDER_GOOGLE_SECRET: ""
      PROVIDER_GITHUB_KEY: ""
      PROVIDER_GITHUB_SECRET: ""
      RECAPTCHA_KEY: ""
      RECAPTCHA_SECRET: ""
    links:
      - mysql_fusio
      - worker_java
      - worker_javascript
      - worker_php
      - worker_python
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./public:/var/www/html/fusio/public

  # Fusio system database
  mysql_fusio:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "61ad6c605975"
      MYSQL_USER: "fusio"
      MYSQL_PASSWORD: "61ad6c605975"
      MYSQL_DATABASE: "fusio"
    volumes:
      - ./db:/var/lib/mysql

  # Worker
  worker_java:
    image: fusio/worker-java
    restart: always
    volumes:
      - ./worker/java:/worker/actions
  worker_javascript:
    image: fusio/worker-javascript
    restart: always
    volumes:
      - ./worker/javascript:/worker/actions
  worker_php:
    image: fusio/worker-php
    restart: always
    volumes:
      - ./worker/php:/worker/actions
  worker_python:
    image: fusio/worker-python
    restart: always
    volumes:
      - ./worker/python:/worker/actions
